### ISSUE TITLE
xcodebuild fails with "/node_modules/@sentry/cli/sentry-cli: cannot execute binary file"

### ISSUE THREAD

**Issue by amast09** [getsentry/react-native-sentry#401]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
bash-3.2$ node -v && npm -v && npm ls --prod --depth=0
v9.10.0
5.6.0
/Users/distiller
└── (empty)
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
  logLevel: SentryLog.Error
}).install()
```

---
I have following issue:

xcodebuild fails during `Bundle React Native code and images` build phase. The build phase has the following content,

```
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
    ../node_modules/react-native/scripts/react-native-xcode.sh
```

The error I get is the following,
```
[19:25:35]: ▸     export arch=arm64
[19:25:35]: ▸     export variant=normal
[19:25:35]: ▸     /bin/sh -c /Users/distiller/project/fastlane/generated/Build/Intermediates.noindex/ArchiveIntermediates/PoolOfficeManager/IntermediateBuildFilesPath/PoolOfficeManager.build/Release-iphoneos/PoolOfficeManager.build/Script-00DD1BFF1BD5951E006B06BC.sh
[19:25:35]: ▸ /Users/distiller/project/node_modules/@sentry/cli/sentry-cli: /Users/distiller/project/node_modules/@sentry/cli/sentry-cli: cannot execute binary file
[19:25:35]: ▸ Command /bin/sh failed with exit code 126
```

I am using,
* Fastlane `2.78.0`
* CircleCI `2.0`
* XCode `9.3`
* React Native `0.53.0`
* React Native Sentry `0.36.0`

### Important Notes
* I am running this on CircleCI.
* If I comment out the Sentry part of the `Bundle React Native code and images` phase the build succeeds.
* The build succeeds when running locally but fails when run in CircleCI.

**Steps to reproduce:**
(Kind of hard to reproduce with CircleCI being involved however this is the xcodebuild command that fails)
- set -o pipefail && xcodebuild -scheme <scheme name> -project ios/<project name>.xcodeproj -configuration Release -destination 'generic/platform=iOS' -archivePath fastlane/generated/POM\ 2018-05-01\ 19.22.13.xcarchive -derivedDataPath 'fastlane/generated' clean archive | tee /Users/distiller/project/fastlane/generated/<log file name>.log | xcpretty

**Actual result:**
- Build fails saying `/Users/distiller/project/node_modules/@sentry/cli/sentry-cli: cannot execute binary file`

**Expected result:**
- Build Succeeds

Please let me know if you need any additional details (React Native + Fastlane + CircleCI + MacOS + Xcode is a lot of moving parts), been trying to fix this for about 7 hours now and any help would be greatly appreciated!

**Comment by HazAT** [comment]
Thanks for the detailed bug report 👍 
This issue is basically about `sentry-cli`.
Still, this is a tough one, we've seen this error if you try to run `sentry-cli` on Alpine Linux but not on Mac.
What you could try is, install `sentry-cli` globally with homebrew or our script see: https://github.com/getsentry/sentry-cli

You have to change the path of `sentry-cli` in your `Run script` phase to call the global one instead of the one from `node_modules`.

**Comment by amast09** [comment]
Thank you for the quick reply. I had actually tried installing the CLI via brew earlier but forgot to update the build phase to use the brew installed version of it.

After updating the build phase to use the system installed CLI as opposed to the node_modules installed CLI it works! 🎉 

Feel free to close this issue or if you want more info to try to address the wonkiness let me know.

Thanks for the help!

**Comment by HazAT** [comment]
@amast09 Great. 
I will close this issue, debugging on a foreign CI isn't really feasible I would say 😅 
But thanks nevertheless 😄

**Comment by jamesmcn1** [comment]
Still experiencing this issue

This is my build phases:
```
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node

# If you are using RN 0.46+
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
../node_modules/react-native/scripts/react-native-xcode.sh
```

I installed via the `sudo npm install -g @sentry/cli --unsafe-perm` but I can't figure out how to change the build phase to target a globally installed version......

**Comment by jamesmcn1** [comment]
@amast09 - hey, please can you share your updated build phase script which uses the brew cli :)

**Comment by amast09** [comment]
@jamesmcn1 here is the relevant sections of my Circle configuration,

```
  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  ios_bundle_cache_key: &ios_bundle_cache_key
    v2-ios-dependency-bundle-{{ checksum "~/project/Gemfile.lock" }}

  ios_bundle_backup_cache_key: &ios_bundle_backup_cache_key
    v2-ios-dependency-bundle

  restore_ios_bundle: &restore_ios_bundle
    restore_cache:
      keys:
        - *ios_bundle_cache_key
        - *ios_bundle_backup_cache_key

  ios_container_config: &ios_container_config
    working_directory: ~/project
    macos:
      xcode: "9.3.0"
    environment:
      - LANG: "en_US.UTF-8"
      - LC_ALL: "en_US.UTF-8"
      - LOCALE: "en_US.UTF-8"
    shell: /bin/bash --login -eo pipefail

  build_ipa:
    <<: *ios_container_config
    steps:
      - *attach_workspace
      - *restore_ios_bundle
      - run:
          name: Install Sentry CLI
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            cd ios && pod install
```

hopefully it can help you 👍
